/**:
  ros__parameters:
    # Flight parameters
    mapping_height: 20.0  # meters
    survey_speed: 5.0  # m/s
    area_length: 100.0  # meters (X direction)
    area_width: 50.0  # meters (Y direction)
    strip_spacing: 10.0  # meters between parallel survey lines
    height_threshold: 0.3  # meters

    # Control parameters
    height_p_gain: 2.0
    max_vertical_velocity: 2.0
    takeoff_velocity: 1.5

    # Camera parameters
    camera_topic: "/camera/image_raw"
    camera_info_topic: "/camera/camera_info"
    
    # ORBSLAM parameters
    slam_vocabulary_path: "package://terrain_mapping_drone_control/config/ORBvoc.txt"
    slam_settings_path: "package://terrain_mapping_drone_control/config/camera_calibration.yaml"
    
    # Output settings
    save_trajectory: true
    trajectory_save_path: "~/terrain_mapping_results" 